name: Plug-in CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - run: npm ci
            - run: npm run build-dev

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  name: ⚗️ Development Build
                  tag_name: dev
                  prerelease: true
                  generate_release_notes: true
                  append_body: |
                      # For testing purposes only, do NOT use in production! ![cnt](https://img.shields.io/github/downloads/volatile-static/Chartero/dev/total)
                  files: build/chartero.xpi
